# si - simple interpreter

PROGRAM_NAME=si

SOURCE_DIR=src

BUILD_DIR=build

INSTALL_TOP=/usr/local

INSTALL_BIN=$(INSTALL_TOP)/bin

LIBS=-lreadline

LIBS_RELEASE=

FLAGS=-o $(BUILD_DIR)/$(PROGRAM_NAME) $(SOURCE_DIR)/*.c -Iinclude -Wall

FLAGS_DEBUG=-g

FLAGS_LOCAL=-O2 -D TRACK_MEMORY -D USE_READLINE $(LIBS)

FLAGS_RELEASE=-O2 -Werror -D NDEBUG $(LIBS_RELEASE)

CC=gcc
